import cclib
from cclib.parser.utils import PeriodicTable


def xyz_from_cclib(path):
    data = cclib.io.ccread(path)
    if data is None:
        raise ValueError(f'cclib can not read file: {path}')

    atomnos = data.atomnos
    coords = data.atomcoords[-1]

    lines = [f'{len(atomnos)}', 'Generated by cclib']

    ptable = PeriodicTable()

    for Z, (x, y, z) in zip(atomnos, coords):
        lines.append(f'{ptable.element[Z]:5s}    {x:13.9f}    {y:13.9f}    {z:13.9f}')

    xyz_string = '\n'.join(lines) + '\n'
    return xyz_string, data

if __name__ == '__main__':
    xyz, data = xyz_from_cclib('../examples/PSB4.log')
    print(xyz)