# Form implementation generated from reading ui file 'IRGuiUI.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_IrDialog(object):
    def setupUi(self, IrDialog):
        IrDialog.setObjectName("IrDialog")
        IrDialog.resize(866, 537)
        self.verticalLayout = QtWidgets.QVBoxLayout(IrDialog)
        self.verticalLayout.setContentsMargins(2, 0, 2, 9)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=IrDialog)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=IrDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.widthlabel = QtWidgets.QLabel(parent=IrDialog)
        self.widthlabel.setObjectName("widthlabel")
        self.horizontalLayout.addWidget(self.widthlabel)
        self.gaussslider = QtWidgets.QSlider(parent=IrDialog)
        self.gaussslider.setTabletTracking(False)
        self.gaussslider.setAutoFillBackground(False)
        self.gaussslider.setMaximum(60)
        self.gaussslider.setSliderPosition(7)
        self.gaussslider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.gaussslider.setInvertedAppearance(False)
        self.gaussslider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksAbove)
        self.gaussslider.setTickInterval(1)
        self.gaussslider.setObjectName("gaussslider")
        self.horizontalLayout.addWidget(self.gaussslider)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 12)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(IrDialog)
        QtCore.QMetaObject.connectSlotsByName(IrDialog)

    def retranslateUi(self, IrDialog):
        _translate = QtCore.QCoreApplication.translate
        IrDialog.setWindowTitle(_translate("IrDialog", "IR Spectrum"))
        self.label.setText(_translate("IrDialog", "Peak width: "))
        self.widthlabel.setText(_translate("IrDialog", "7 "))
