# Form implementation generated from reading ui file 'MainGuiui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_analyzer(object):
    def setupUi(self, analyzer):
        analyzer.setObjectName("analyzer")
        analyzer.resize(878, 610)
        self.centralwidget = QtWidgets.QWidget(parent=analyzer)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.molviewer = QtWidgets.QWidget(parent=self.centralwidget)
        self.molviewer.setObjectName("molviewer")
        self.horizontalLayout.addWidget(self.molviewer)
        analyzer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=analyzer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSpectroscopy = QtWidgets.QMenu(parent=self.menubar)
        self.menuSpectroscopy.setObjectName("menuSpectroscopy")
        self.menuGeometry = QtWidgets.QMenu(parent=self.menubar)
        self.menuGeometry.setObjectName("menuGeometry")
        analyzer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=analyzer)
        self.statusbar.setObjectName("statusbar")
        analyzer.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(parent=analyzer)
        self.actionOpen.setObjectName("actionOpen")
        self.actionIR = QtGui.QAction(parent=analyzer)
        self.actionIR.setObjectName("actionIR")
        self.actionUV = QtGui.QAction(parent=analyzer)
        self.actionUV.setObjectName("actionUV")
        self.actionBond_lengths = QtGui.QAction(parent=analyzer)
        self.actionBond_lengths.setObjectName("actionBond_lengths")
        self.actionAngles = QtGui.QAction(parent=analyzer)
        self.actionAngles.setObjectName("actionAngles")
        self.actionDihedrals = QtGui.QAction(parent=analyzer)
        self.actionDihedrals.setObjectName("actionDihedrals")
        self.menuFile.addAction(self.actionOpen)
        self.menuSpectroscopy.addAction(self.actionIR)
        self.menuSpectroscopy.addAction(self.actionUV)
        self.menuGeometry.addAction(self.actionBond_lengths)
        self.menuGeometry.addAction(self.actionAngles)
        self.menuGeometry.addAction(self.actionDihedrals)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSpectroscopy.menuAction())
        self.menubar.addAction(self.menuGeometry.menuAction())

        self.retranslateUi(analyzer)
        QtCore.QMetaObject.connectSlotsByName(analyzer)

    def retranslateUi(self, analyzer):
        _translate = QtCore.QCoreApplication.translate
        analyzer.setWindowTitle(_translate("analyzer", "PyQuanAnalizer"))
        self.menuFile.setTitle(_translate("analyzer", "File"))
        self.menuSpectroscopy.setTitle(_translate("analyzer", "Spectroscopy"))
        self.menuGeometry.setTitle(_translate("analyzer", "Geometry"))
        self.actionOpen.setText(_translate("analyzer", "Open"))
        self.actionOpen.setShortcut(_translate("analyzer", "Ctrl+O"))
        self.actionIR.setText(_translate("analyzer", "IR"))
        self.actionUV.setText(_translate("analyzer", "UV"))
        self.actionBond_lengths.setText(_translate("analyzer", "Bond lengths"))
        self.actionAngles.setText(_translate("analyzer", "Angles"))
        self.actionDihedrals.setText(_translate("analyzer", "Dihedrals"))
